# Generated by Django 2.2 on 2021-05-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210502_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='finality',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
